version: '2'
services:
  core:
    build: .
    ports:
      - '8080:8080'
      - '8787:8787'
      - '9990:9990'
    volumes:
      - ./serviceblbnavi-ear/deployments:/opt/jboss/wildfly/standalone/deployments
    depends_on:
      - db
      - db_prod
    environment:
      TZ: Europe/Warsaw
      APP_ENVIRONMENT: development
      APP_DB_HOST: db
      APP_DB_HOST_PROD: db_prod
    entrypoint: ["wait-for-container-end", "-c", "liquibase", "-c", "liquibase_prod", "--", "/start-server.sh"]

  db:
    extends:
      file: database/docker-compose.yml
      service: db

  db_prod:
    extends:
      file: database/docker-compose.yml
      service: db_prod

  liquibase:
    extends:
      file: database/docker-compose.yml
      service: liquibase

  liquibase_prod:
    extends:
      file: database/docker-compose.yml
      service: liquibase_prod

volumes:
  # For Liquibase container.
  maven_liquibase: {}