version: '2'
services:
  core:
    build: .
    ports:
      - '80:8080'
      - '8787:8787'
      - '9990:9990'
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments
    depends_on:
      - db
    environment:
      TZ: Europe/Warsaw
      APP_ENVIRONMENT: development
      APP_DB_HOST: db
    entrypoint: ["wait-for-it", "db:3306", "-t", "0", "--", "/start-server.sh"]

  db:
    extends:
      file: database/docker-compose.yml
      service: db

  liquibase:
    extends:
      file: database/docker-compose.yml
      service: liquibase

volumes:
  # For Liquibase container.
  maven_liquibase: {}
