// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: measure.proto

package co.blastlab.indoornavi.socket.measures.model;

public final class MeasuresPackage {
  private MeasuresPackage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MeasuresOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Measures)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    java.util.List<co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure> 
        getMeasuresList();
    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure getMeasures(int index);
    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    int getMeasuresCount();
    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    java.util.List<? extends co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder> 
        getMeasuresOrBuilderList();
    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder getMeasuresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Measures}
   */
  public  static final class Measures extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Measures)
      MeasuresOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Measures.newBuilder() to construct.
    private Measures(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Measures() {
      measures_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Measures(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                measures_ = new java.util.ArrayList<co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure>();
                mutable_bitField0_ |= 0x00000001;
              }
              measures_.add(
                  input.readMessage(co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          measures_ = java.util.Collections.unmodifiableList(measures_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.class, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Builder.class);
    }

    public interface MeasureOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Measures.Measure)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required sfixed32 did1 = 1;</code>
       */
      boolean hasDid1();
      /**
       * <code>required sfixed32 did1 = 1;</code>
       */
      int getDid1();

      /**
       * <code>required sfixed32 did2 = 2;</code>
       */
      boolean hasDid2();
      /**
       * <code>required sfixed32 did2 = 2;</code>
       */
      int getDid2();

      /**
       * <code>required sfixed32 dist = 3;</code>
       */
      boolean hasDist();
      /**
       * <code>required sfixed32 dist = 3;</code>
       */
      int getDist();

      /**
       * <pre>
       * first path power
       * </pre>
       *
       * <code>required sfixed32 fpp = 4;</code>
       */
      boolean hasFpp();
      /**
       * <pre>
       * first path power
       * </pre>
       *
       * <code>required sfixed32 fpp = 4;</code>
       */
      int getFpp();

      /**
       * <code>required sfixed32 signal = 5;</code>
       */
      boolean hasSignal();
      /**
       * <code>required sfixed32 signal = 5;</code>
       */
      int getSignal();

      /**
       * <code>required fixed64 time = 6;</code>
       */
      boolean hasTime();
      /**
       * <code>required fixed64 time = 6;</code>
       */
      long getTime();
    }
    /**
     * Protobuf type {@code Measures.Measure}
     */
    public  static final class Measure extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Measures.Measure)
        MeasureOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Measure.newBuilder() to construct.
      private Measure(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Measure() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Measure(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                bitField0_ |= 0x00000001;
                did1_ = input.readSFixed32();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                did2_ = input.readSFixed32();
                break;
              }
              case 29: {
                bitField0_ |= 0x00000004;
                dist_ = input.readSFixed32();
                break;
              }
              case 37: {
                bitField0_ |= 0x00000008;
                fpp_ = input.readSFixed32();
                break;
              }
              case 45: {
                bitField0_ |= 0x00000010;
                signal_ = input.readSFixed32();
                break;
              }
              case 49: {
                bitField0_ |= 0x00000020;
                time_ = input.readFixed64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_Measure_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_Measure_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.class, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder.class);
      }

      private int bitField0_;
      public static final int DID1_FIELD_NUMBER = 1;
      private int did1_;
      /**
       * <code>required sfixed32 did1 = 1;</code>
       */
      public boolean hasDid1() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required sfixed32 did1 = 1;</code>
       */
      public int getDid1() {
        return did1_;
      }

      public static final int DID2_FIELD_NUMBER = 2;
      private int did2_;
      /**
       * <code>required sfixed32 did2 = 2;</code>
       */
      public boolean hasDid2() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required sfixed32 did2 = 2;</code>
       */
      public int getDid2() {
        return did2_;
      }

      public static final int DIST_FIELD_NUMBER = 3;
      private int dist_;
      /**
       * <code>required sfixed32 dist = 3;</code>
       */
      public boolean hasDist() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required sfixed32 dist = 3;</code>
       */
      public int getDist() {
        return dist_;
      }

      public static final int FPP_FIELD_NUMBER = 4;
      private int fpp_;
      /**
       * <pre>
       * first path power
       * </pre>
       *
       * <code>required sfixed32 fpp = 4;</code>
       */
      public boolean hasFpp() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * first path power
       * </pre>
       *
       * <code>required sfixed32 fpp = 4;</code>
       */
      public int getFpp() {
        return fpp_;
      }

      public static final int SIGNAL_FIELD_NUMBER = 5;
      private int signal_;
      /**
       * <code>required sfixed32 signal = 5;</code>
       */
      public boolean hasSignal() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required sfixed32 signal = 5;</code>
       */
      public int getSignal() {
        return signal_;
      }

      public static final int TIME_FIELD_NUMBER = 6;
      private long time_;
      /**
       * <code>required fixed64 time = 6;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required fixed64 time = 6;</code>
       */
      public long getTime() {
        return time_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDid1()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDid2()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDist()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFpp()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSignal()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTime()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeSFixed32(1, did1_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeSFixed32(2, did2_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeSFixed32(3, dist_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          output.writeSFixed32(4, fpp_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          output.writeSFixed32(5, signal_);
        }
        if (((bitField0_ & 0x00000020) != 0)) {
          output.writeFixed64(6, time_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSFixed32Size(1, did1_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSFixed32Size(2, did2_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSFixed32Size(3, dist_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSFixed32Size(4, fpp_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSFixed32Size(5, signal_);
        }
        if (((bitField0_ & 0x00000020) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed64Size(6, time_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure)) {
          return super.equals(obj);
        }
        co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure other = (co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure) obj;

        if (hasDid1() != other.hasDid1()) return false;
        if (hasDid1()) {
          if (getDid1()
              != other.getDid1()) return false;
        }
        if (hasDid2() != other.hasDid2()) return false;
        if (hasDid2()) {
          if (getDid2()
              != other.getDid2()) return false;
        }
        if (hasDist() != other.hasDist()) return false;
        if (hasDist()) {
          if (getDist()
              != other.getDist()) return false;
        }
        if (hasFpp() != other.hasFpp()) return false;
        if (hasFpp()) {
          if (getFpp()
              != other.getFpp()) return false;
        }
        if (hasSignal() != other.hasSignal()) return false;
        if (hasSignal()) {
          if (getSignal()
              != other.getSignal()) return false;
        }
        if (hasTime() != other.hasTime()) return false;
        if (hasTime()) {
          if (getTime()
              != other.getTime()) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasDid1()) {
          hash = (37 * hash) + DID1_FIELD_NUMBER;
          hash = (53 * hash) + getDid1();
        }
        if (hasDid2()) {
          hash = (37 * hash) + DID2_FIELD_NUMBER;
          hash = (53 * hash) + getDid2();
        }
        if (hasDist()) {
          hash = (37 * hash) + DIST_FIELD_NUMBER;
          hash = (53 * hash) + getDist();
        }
        if (hasFpp()) {
          hash = (37 * hash) + FPP_FIELD_NUMBER;
          hash = (53 * hash) + getFpp();
        }
        if (hasSignal()) {
          hash = (37 * hash) + SIGNAL_FIELD_NUMBER;
          hash = (53 * hash) + getSignal();
        }
        if (hasTime()) {
          hash = (37 * hash) + TIME_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getTime());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Measures.Measure}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Measures.Measure)
          co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_Measure_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_Measure_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.class, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder.class);
        }

        // Construct using co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          did1_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          did2_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          dist_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          fpp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          signal_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          time_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_Measure_descriptor;
        }

        @java.lang.Override
        public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure getDefaultInstanceForType() {
          return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.getDefaultInstance();
        }

        @java.lang.Override
        public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure build() {
          co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure buildPartial() {
          co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure result = new co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.did1_ = did1_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.did2_ = did2_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.dist_ = dist_;
            to_bitField0_ |= 0x00000004;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.fpp_ = fpp_;
            to_bitField0_ |= 0x00000008;
          }
          if (((from_bitField0_ & 0x00000010) != 0)) {
            result.signal_ = signal_;
            to_bitField0_ |= 0x00000010;
          }
          if (((from_bitField0_ & 0x00000020) != 0)) {
            result.time_ = time_;
            to_bitField0_ |= 0x00000020;
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure) {
            return mergeFrom((co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure other) {
          if (other == co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.getDefaultInstance()) return this;
          if (other.hasDid1()) {
            setDid1(other.getDid1());
          }
          if (other.hasDid2()) {
            setDid2(other.getDid2());
          }
          if (other.hasDist()) {
            setDist(other.getDist());
          }
          if (other.hasFpp()) {
            setFpp(other.getFpp());
          }
          if (other.hasSignal()) {
            setSignal(other.getSignal());
          }
          if (other.hasTime()) {
            setTime(other.getTime());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasDid1()) {
            return false;
          }
          if (!hasDid2()) {
            return false;
          }
          if (!hasDist()) {
            return false;
          }
          if (!hasFpp()) {
            return false;
          }
          if (!hasSignal()) {
            return false;
          }
          if (!hasTime()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int did1_ ;
        /**
         * <code>required sfixed32 did1 = 1;</code>
         */
        public boolean hasDid1() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required sfixed32 did1 = 1;</code>
         */
        public int getDid1() {
          return did1_;
        }
        /**
         * <code>required sfixed32 did1 = 1;</code>
         */
        public Builder setDid1(int value) {
          bitField0_ |= 0x00000001;
          did1_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required sfixed32 did1 = 1;</code>
         */
        public Builder clearDid1() {
          bitField0_ = (bitField0_ & ~0x00000001);
          did1_ = 0;
          onChanged();
          return this;
        }

        private int did2_ ;
        /**
         * <code>required sfixed32 did2 = 2;</code>
         */
        public boolean hasDid2() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required sfixed32 did2 = 2;</code>
         */
        public int getDid2() {
          return did2_;
        }
        /**
         * <code>required sfixed32 did2 = 2;</code>
         */
        public Builder setDid2(int value) {
          bitField0_ |= 0x00000002;
          did2_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required sfixed32 did2 = 2;</code>
         */
        public Builder clearDid2() {
          bitField0_ = (bitField0_ & ~0x00000002);
          did2_ = 0;
          onChanged();
          return this;
        }

        private int dist_ ;
        /**
         * <code>required sfixed32 dist = 3;</code>
         */
        public boolean hasDist() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>required sfixed32 dist = 3;</code>
         */
        public int getDist() {
          return dist_;
        }
        /**
         * <code>required sfixed32 dist = 3;</code>
         */
        public Builder setDist(int value) {
          bitField0_ |= 0x00000004;
          dist_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required sfixed32 dist = 3;</code>
         */
        public Builder clearDist() {
          bitField0_ = (bitField0_ & ~0x00000004);
          dist_ = 0;
          onChanged();
          return this;
        }

        private int fpp_ ;
        /**
         * <pre>
         * first path power
         * </pre>
         *
         * <code>required sfixed32 fpp = 4;</code>
         */
        public boolean hasFpp() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <pre>
         * first path power
         * </pre>
         *
         * <code>required sfixed32 fpp = 4;</code>
         */
        public int getFpp() {
          return fpp_;
        }
        /**
         * <pre>
         * first path power
         * </pre>
         *
         * <code>required sfixed32 fpp = 4;</code>
         */
        public Builder setFpp(int value) {
          bitField0_ |= 0x00000008;
          fpp_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * first path power
         * </pre>
         *
         * <code>required sfixed32 fpp = 4;</code>
         */
        public Builder clearFpp() {
          bitField0_ = (bitField0_ & ~0x00000008);
          fpp_ = 0;
          onChanged();
          return this;
        }

        private int signal_ ;
        /**
         * <code>required sfixed32 signal = 5;</code>
         */
        public boolean hasSignal() {
          return ((bitField0_ & 0x00000010) != 0);
        }
        /**
         * <code>required sfixed32 signal = 5;</code>
         */
        public int getSignal() {
          return signal_;
        }
        /**
         * <code>required sfixed32 signal = 5;</code>
         */
        public Builder setSignal(int value) {
          bitField0_ |= 0x00000010;
          signal_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required sfixed32 signal = 5;</code>
         */
        public Builder clearSignal() {
          bitField0_ = (bitField0_ & ~0x00000010);
          signal_ = 0;
          onChanged();
          return this;
        }

        private long time_ ;
        /**
         * <code>required fixed64 time = 6;</code>
         */
        public boolean hasTime() {
          return ((bitField0_ & 0x00000020) != 0);
        }
        /**
         * <code>required fixed64 time = 6;</code>
         */
        public long getTime() {
          return time_;
        }
        /**
         * <code>required fixed64 time = 6;</code>
         */
        public Builder setTime(long value) {
          bitField0_ |= 0x00000020;
          time_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required fixed64 time = 6;</code>
         */
        public Builder clearTime() {
          bitField0_ = (bitField0_ & ~0x00000020);
          time_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Measures.Measure)
      }

      // @@protoc_insertion_point(class_scope:Measures.Measure)
      private static final co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure();
      }

      public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Measure>
          PARSER = new com.google.protobuf.AbstractParser<Measure>() {
        @java.lang.Override
        public Measure parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Measure(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Measure> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Measure> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MEASURES_FIELD_NUMBER = 1;
    private java.util.List<co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure> measures_;
    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    public java.util.List<co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure> getMeasuresList() {
      return measures_;
    }
    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    public java.util.List<? extends co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder> 
        getMeasuresOrBuilderList() {
      return measures_;
    }
    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    public int getMeasuresCount() {
      return measures_.size();
    }
    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure getMeasures(int index) {
      return measures_.get(index);
    }
    /**
     * <code>repeated .Measures.Measure measures = 1;</code>
     */
    public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder getMeasuresOrBuilder(
        int index) {
      return measures_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getMeasuresCount(); i++) {
        if (!getMeasures(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < measures_.size(); i++) {
        output.writeMessage(1, measures_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < measures_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, measures_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures)) {
        return super.equals(obj);
      }
      co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures other = (co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures) obj;

      if (!getMeasuresList()
          .equals(other.getMeasuresList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMeasuresCount() > 0) {
        hash = (37 * hash) + MEASURES_FIELD_NUMBER;
        hash = (53 * hash) + getMeasuresList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Measures}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Measures)
        co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.MeasuresOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.class, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Builder.class);
      }

      // Construct using co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMeasuresFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (measuresBuilder_ == null) {
          measures_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          measuresBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.internal_static_Measures_descriptor;
      }

      @java.lang.Override
      public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures getDefaultInstanceForType() {
        return co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.getDefaultInstance();
      }

      @java.lang.Override
      public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures build() {
        co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures buildPartial() {
        co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures result = new co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures(this);
        int from_bitField0_ = bitField0_;
        if (measuresBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            measures_ = java.util.Collections.unmodifiableList(measures_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.measures_ = measures_;
        } else {
          result.measures_ = measuresBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures) {
          return mergeFrom((co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures other) {
        if (other == co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.getDefaultInstance()) return this;
        if (measuresBuilder_ == null) {
          if (!other.measures_.isEmpty()) {
            if (measures_.isEmpty()) {
              measures_ = other.measures_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMeasuresIsMutable();
              measures_.addAll(other.measures_);
            }
            onChanged();
          }
        } else {
          if (!other.measures_.isEmpty()) {
            if (measuresBuilder_.isEmpty()) {
              measuresBuilder_.dispose();
              measuresBuilder_ = null;
              measures_ = other.measures_;
              bitField0_ = (bitField0_ & ~0x00000001);
              measuresBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMeasuresFieldBuilder() : null;
            } else {
              measuresBuilder_.addAllMessages(other.measures_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getMeasuresCount(); i++) {
          if (!getMeasures(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure> measures_ =
        java.util.Collections.emptyList();
      private void ensureMeasuresIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          measures_ = new java.util.ArrayList<co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure>(measures_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder> measuresBuilder_;

      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public java.util.List<co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure> getMeasuresList() {
        if (measuresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(measures_);
        } else {
          return measuresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public int getMeasuresCount() {
        if (measuresBuilder_ == null) {
          return measures_.size();
        } else {
          return measuresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure getMeasures(int index) {
        if (measuresBuilder_ == null) {
          return measures_.get(index);
        } else {
          return measuresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public Builder setMeasures(
          int index, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure value) {
        if (measuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasuresIsMutable();
          measures_.set(index, value);
          onChanged();
        } else {
          measuresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public Builder setMeasures(
          int index, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder builderForValue) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.set(index, builderForValue.build());
          onChanged();
        } else {
          measuresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public Builder addMeasures(co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure value) {
        if (measuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasuresIsMutable();
          measures_.add(value);
          onChanged();
        } else {
          measuresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public Builder addMeasures(
          int index, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure value) {
        if (measuresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMeasuresIsMutable();
          measures_.add(index, value);
          onChanged();
        } else {
          measuresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public Builder addMeasures(
          co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder builderForValue) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.add(builderForValue.build());
          onChanged();
        } else {
          measuresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public Builder addMeasures(
          int index, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder builderForValue) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.add(index, builderForValue.build());
          onChanged();
        } else {
          measuresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public Builder addAllMeasures(
          java.lang.Iterable<? extends co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure> values) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, measures_);
          onChanged();
        } else {
          measuresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public Builder clearMeasures() {
        if (measuresBuilder_ == null) {
          measures_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          measuresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public Builder removeMeasures(int index) {
        if (measuresBuilder_ == null) {
          ensureMeasuresIsMutable();
          measures_.remove(index);
          onChanged();
        } else {
          measuresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder getMeasuresBuilder(
          int index) {
        return getMeasuresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder getMeasuresOrBuilder(
          int index) {
        if (measuresBuilder_ == null) {
          return measures_.get(index);  } else {
          return measuresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public java.util.List<? extends co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder> 
           getMeasuresOrBuilderList() {
        if (measuresBuilder_ != null) {
          return measuresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(measures_);
        }
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder addMeasuresBuilder() {
        return getMeasuresFieldBuilder().addBuilder(
            co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.getDefaultInstance());
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder addMeasuresBuilder(
          int index) {
        return getMeasuresFieldBuilder().addBuilder(
            index, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.getDefaultInstance());
      }
      /**
       * <code>repeated .Measures.Measure measures = 1;</code>
       */
      public java.util.List<co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder> 
           getMeasuresBuilderList() {
        return getMeasuresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder> 
          getMeasuresFieldBuilder() {
        if (measuresBuilder_ == null) {
          measuresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.Measure.Builder, co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures.MeasureOrBuilder>(
                  measures_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          measures_ = null;
        }
        return measuresBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Measures)
    }

    // @@protoc_insertion_point(class_scope:Measures)
    private static final co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures();
    }

    public static co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Measures>
        PARSER = new com.google.protobuf.AbstractParser<Measures>() {
      @java.lang.Override
      public Measures parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Measures(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Measures> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Measures> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public co.blastlab.indoornavi.socket.measures.model.MeasuresPackage.Measures getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Measures_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Measures_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Measures_Measure_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Measures_Measure_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmeasure.proto\"\217\001\n\010Measures\022#\n\010measures" +
      "\030\001 \003(\0132\021.Measures.Measure\032^\n\007Measure\022\014\n\004" +
      "did1\030\001 \002(\017\022\014\n\004did2\030\002 \002(\017\022\014\n\004dist\030\003 \002(\017\022\013" +
      "\n\003fpp\030\004 \002(\017\022\016\n\006signal\030\005 \002(\017\022\014\n\004time\030\006 \002(" +
      "\006B?\n,co.blastlab.indoornavi.socket.measu" +
      "res.modelB\017MeasuresPackage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Measures_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Measures_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Measures_descriptor,
        new java.lang.String[] { "Measures", });
    internal_static_Measures_Measure_descriptor =
      internal_static_Measures_descriptor.getNestedTypes().get(0);
    internal_static_Measures_Measure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Measures_Measure_descriptor,
        new java.lang.String[] { "Did1", "Did2", "Dist", "Fpp", "Signal", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
